### ISSUE TITLE
Using `babel-plugin-lodash` with redux-actions

### ISSUE THREAD

**Issue by rhys-vdw** [redux-utilities/redux-actions#223]
It looks to me as though this project could be used in conjunction with `babel-plugin-lodash`.

If this is intentional, then perhaps your README could also contain [this section from recompose](https://github.com/acdlite/recompose#using-babel-lodash-plugin).

**Comment by yangmillstheory** [comment]
Are you suggesting that we use `babel-plugin-lodash`?

We're using https://github.com/acdlite/redux-actions/blob/master/.babelrc#L9 currently; I'm not sure what the difference is.

**Comment by rhys-vdw** [comment]
No, sorry. I'm suggesting that because you have your file structure like this:

```js
import { createAction as foo } from 'redux-actions'
import bar from 'redux-actions/createAction'
assert.equal(foo, bar)
```

Consumers of your library can take advantage of this by using `babel-plugin-lodash` to reduce build size by transforming their source from:

```js
import { createAction } from 'redux-actions'
```

to

```js
import createAction from 'redux-actions/createAction'
```

**Comment by rhys-vdw** [comment]
(Although you could use babel-plugin-lodash internally instead of the custom lodash-es loader you've got, that's a separate issue that I have no opinion on)

**Comment by timche** [comment]
We have removed `lodash` in v2.5.0: https://github.com/redux-utilities/redux-actions/releases/tag/v2.5.0

**Comment by rhys-vdw** [comment]
@timche This issue has nothing to do with your consumption of lodash, but is a recommendation that you make the library compatible with `babel-plugin-lodash`.

**Comment by rhys-vdw** [comment]
:-( can't really think of a way to explain this any more clearly

**Comment by timche** [comment]
Sorry, I haven't read carefully as it was just confusing me to read `lodash` all the time. I got your point now.

**Comment by timche** [comment]
So if anyone has time and wants to open a PR for some extra documentation, feel free, thanks 🙏
