### ISSUE TITLE
`combineActions` incompatible with recursive `handleActions`.

### ISSUE THREAD

**Issue by Parakleta** [redux-utilities/redux-actions#241]
When using the recursive form of `handleActions` it only attaches the current path to the first option from `combineActions`.  It needs instead to re-separate the combined actions and attach the path to each of them before re-joining them.

**Comment by Parakleta** [comment]
Consider changing https://github.com/reduxactions/redux-actions/blob/4f6413ae1f4344350d1479446e8de4e8fa6d02d1/src/flattenUtils.js#L14-L18 to something like

```js
import { ACTION_TYPE_DELIMITER } from './combineActions';
function connectNamespace(type) {
    if (!partialFlatActionType) return type;
    const types = type.toString().split(ACTION_TYPE_DELIMITER);
    const partials = partialFlatActionType.split(ACTION_TYPE_DELIMITER);
    return [].concat(...partials.map(p => types.map(t => p + namespace + t)))
        .join(ACTION_TYPE_DELIMITER);
}
```

**Comment by victordidenko** [comment]
Is it going to be implemented?
