### ISSUE TITLE
Host redux-actions.js.org in https://github.com/reduxactions/

### ISSUE THREAD

**Issue by yangmillstheory** [redux-utilities/redux-actions#243]
Currently it's hosted on https://vinnymac.gitbooks.io/redux-actions/ cc: @vinnymac

**Comment by vinnymac** [comment]
@yangmillstheory I gave you admin access on the gitbook. We can unlink it from my repo and link it to reduxactions/redux-actions or other, do you now have access to the settings page?

**Comment by timche** [comment]
We have access now.

**Comment by yangmillstheory** [comment]
Yep, we just need to find the time to actually do the migration. This issue
is just a placeholder.

**Comment by timche** [comment]
Resolved.
