### ISSUE TITLE
`prefix` option for `createActions`

### ISSUE THREAD

**Issue by rqrqrqrq** [redux-utilities/redux-actions#263]
As I know there are a lot of folks writing something like this following [ducks proposal](https://github.com/erikras/ducks-modular-redux):
```js
const prefix = 'some-feature';

const { [prefix]: actionCreators } = createActions(
  {
    [prefix]: {
      SOME_ACTION: payloadCreator,
    },
  }, 
  `${prefix}/PLAIN_ACTION`,
);
```
This looks kinda hacky. Can we consider adding `prefix` in `options` for `createActions` to handle this common case?
```js
const actionCreators = createActions(
  {
    SOME_ACTION: payloadCreator,
  },
  'PLAIN_ACTION',
  {
    prefix: 'some-feature',
  },
);
```
Will create pull request if this will be helpful.

**Comment by mslipper** [comment]
This is a great idea. Please open a PR and I'll review.

**Comment by dfernandez79** [comment]
You can also use [lodash] `mapKeys` as a workaround when using objects for actions: 

```js
import mapKeys from 'lodash/mapKeys'
const prefix = name => (value, key) => `${name}key`
const actions = createActions(mapKeys({
   SOME_ACTION: payloadCreator
}, prefix('some-feature/')))
```

Identity actions will require a different treatment 🙁

Shameless plug, I use action type prefixes too when combining reducers, so I end creating my anti-redux boilerplate lib: https://github.com/dfernandez79/redux-heretic
It doesn't follow the ducks proposal, but it fits my limited needs.

[lodash]: https://lodash.com/docs/#mapKeys

**Comment by raythree** [comment]
I would really like to be able to write:
```
const { createPost, deletePost } = createActions('my/app/CREATE_POST', 'my/app/DELETE_POST');
```
Such that it would just use the last part as the action creator name, and createPost.toString() would be 'my/app/CREATE_POST', which could be referenced in other reducers.

**Comment by rqrqrqrq** [comment]
@raythree With this proposal it will be possible to write:
```
const { createPost, deletePost } = createActions(
  'CREATE_POST', 
  'DELETE_POST', 
  { prefix: 'my/app' },
);
```
Is it works for you?

**Comment by raythree** [comment]
Perfect. Thanks!

**Comment by mslipper** [comment]
This is merged. Will talk to @yangmillstheory about releasing it.

**Comment by timche** [comment]
I'll take a look if I can add u as admin to the npm registry.

**Comment by timche** [comment]
@mslipper I've added you as collaborator on npm. You should be able to publish too.

**Comment by mslipper** [comment]
Perfect, thanks @timche!

**Comment by mslipper** [comment]
Merged and released.

**Comment by udalrich** [comment]
Is this documented anywhere other than this issue?

**Comment by freund17** [comment]
I, too, was unable to find the documentation on this...
I expected it to be somewhere on this page: https://redux-actions.js.org/api-reference/createaction-s
