### ISSUE TITLE
Documentation Needs Updating

### ISSUE THREAD

**Issue by larkintuckerllc** [redux-utilities/redux-actions#271]
This is a issue for discussing a current push towards updating the documentation.

**Comment by larkintuckerllc** [comment]
Have done a fairly complete review of the documentation (actually learned a lot), the biggest area for improvement that I see is in the _Motivation_ and _Tutorial_ sections, e.g., the approach on handling errors is pretty amazing and not apparent from these sections.  As part of the review, I spent time writing a separate series of articles on Medium that captures a lot of what I believe would be helpful to incorporate.
<https://medium.com/@johntucker_48673/redux-actions-through-example-part-1-f5b2dc71de06>

**Comment by mslipper** [comment]
This is awesome! Would love to incorporate these posts into the Motivation/Tutorial sections.

**Comment by larkintuckerllc** [comment]
Before I started to propose to make changes to the documentation, I sat down and documented how the documentation was organized (that is a mouthful).  Was sufficiently interesting, that I wrote yet another Medium article on it:

https://medium.com/@johntucker_48673/open-source-documentation-by-example-8599c81d4ab7

**Comment by larkintuckerllc** [comment]
BTW... Through the documentation, it seems that the files in the _docs_ folder have been updated but the generated web site was not re-generated.  This seems to be the first order of business (either manual or with Travis CI).

**Comment by timche** [comment]
This has been fixed, because the docs were based on a fork by a contributor. It's now in sync with `docs` on `master`.
