### ISSUE TITLE
No way shown to have multiple dispatches

### ISSUE THREAD

**Issue by thorakmedichi** [redux-utilities/redux-actions#277]
I find that in a lot of our code we will call a single action creator that will dispatch to multiple reducers after a single API call.

I cant find anything in the documentation that supports that. It appears you can only dispatch to a single reducer type from a single action. Is this true or can someone point me to some documentation on that. 

Google seems to think "redux-actions" is the same as "Redux Actions" so I keep getting results related to what an action and reducer are

**Comment by timche** [comment]
> It appears you can only dispatch to a single reducer type from a single action.

Reducers are listening to the `type` property of the action object, so when dispatching an action, multiple reducers can react to that and that's not related to `redux-actions`, it's a basic of Redux itself.

```js
dispatch({ type: 'FOO' })

const reducerA = (state, action) => {
  if (action.type === 'FOO) {
    // do something
  }
}

const reducerB = (state, action) => {
  if (action.type === 'FOO) {
    // do something
  }
}
```

**Comment by thorakmedichi** [comment]
Sorry, missunderstanding the question. How do I do multiple dispatches from an action. So it dispatches multiple types.

**Comment by timche** [comment]
You'll need something like redux-thunk: https://github.com/gaearon/redux-thunk

**Comment by thorakmedichi** [comment]
Here is an example of what we currently do with redux / thunk... but we would like to start using redux-actions

``
export const pollForChatsAction = (page = 1, limit = CHAT_REQUEST_LIMIT, lastPoll) => {
    const ENDPOINT = `/agent/chats`;

    return (dispatch, getState) => {
        const state = getState();
        const agentId = state.agent.agentId;

        // If the lastPoll is not passed try and get it from the state
        if (lastPoll === undefined || lastPoll === null){
            if (state.polling.chats.lastPoll) {
                lastPoll = state.polling.chats.lastPoll;
            } else {
                lastPoll = moment(new Date().getTime() - CHAT_POLLING_INITIAL_POLL_OFFSET).utc().format();
            }
        }

        const QUERY_STRING = `?${generateQueryString(page, limit, lastPoll)}&` + corsDebug();

        dispatch({
            type: SET_IS_FETCHING_POLLED_CHAT,
            isFetching: true
        });

        return axios.get(`${API_ROOT_URL}${ENDPOINT}${QUERY_STRING}`, setupAjaxHeaders())
            .then((response) => {
                const normalizedData = normalizeChatData(response.data);

                dispatch({
                    type: SET_LAST_POLL_CHAT,
                    lastPoll: moment(response.headers['x-request-date']).utc().format(),
                });

                if (!_.isEmpty(normalizedData.entities)) {
                    dispatch({
                        type: ADD_POLLED_CHATS,
                        byId: normalizedData.entities.chat,
                        ids: categorize(normalizedData.entities.chat, agentId)
                    });
                }

                // If there is more than one page worth of data lets run this function again
                const totalPages = parseInt(response.headers['x-pagination-pages']);
                if (totalPages > 1 && page <= totalPages) {
                    page++;
                    dispatch(pollForChatsAction(page, CHAT_REQUEST_LIMIT, String(lastPoll)));
                }
            })
            .catch((error) => {
                dispatch({
                    type: SET_IS_FETCHING_POLLED_CHAT,
                    isFetching: false
                });

                errorHandler(error);
            });
    };
};
``
