### ISSUE TITLE
How to properly use TypeScript with redux-actions?

### ISSUE THREAD

**Issue by rdsedmundo** [redux-utilities/redux-actions#282]
Hi.

I couldn't get my typings to work with `redux-actions`. Would be great to have a section in the documentation showing the usage.

It's always returning a failure of typings, I don't understand what else I need to do in order to make it work.

This "works":

```typescript
const reducer: Reducer<State> = handleActions<State>(
  {
    [actions.request.toString()]: (state: State, payload) => ({
      ...state,
      someData: payload,
    }),
   initialState,
);
```

The problem starts when I try to add types to my payload. None of below worked:

```typescript
const reducer: Reducer<State> = handleActions<State>(
  {
    [actions.request.toString()]: (state: State, payload: Payload) => ({
      ...state,
      someData: payload,
    }),
   initialState,
);

const reducer: Reducer<State> = handleActions<State, Payload>(
  {
    [actions.request.toString()]: (state: State, payload: Payload) => ({
      ...state,
      someData: payload,
    }),
   initialState,
);
```

I'm having the same difficulties for using `createActions`.

**Comment by timche** [comment]
From where did you get the types? We don't have types (yet).

**Comment by rdsedmundo** [comment]
https://www.npmjs.com/package/@types/redux-actions

I thought it was official. lol

**Comment by rdsedmundo** [comment]
These definitions were written by Jack Hsu @jaysoo, Alex Gorbatchev @alexgorbatchev, Alec Hill @alechill. Any of you guys could help here? It sounds a good opportunity to make it official. 💯

**Comment by timche** [comment]
Unfortunately I can't really help with this, but I'd be happy if we could have them here.

**Comment by dannysood** [comment]
Just a beginner with typescript but would love to see them integrated. typescript seems pretty powerful.

**Comment by Vandell63** [comment]
Hey there same issue for me. For now i use this technique that seams to be ok : 
Remove first the @types/redux-actions ( unfortunatly );

```
import { handleActions } from "redux-actions";

const reducer: Reducer<State> = handleActions( /// <=== do not specified <State>
  {
    [actions.request.toString()]: (state: State, payload: Payload) => ({
      ...state,
      someData: payload,
    }),
   initialState,
);
```
you keep your strong type...

**Comment by karol-majewski** [comment]
The way I've used `handleActions` so far is by employing two type parameters:

1. The shape of your reducer. (Here: `Reducers.Marketplaces`.)
2. The union of all action payloads coming through your reducer. (Here: `string`.)

A real-life example might look like this:

```ts
export default handleActions<Reducers.Marketplaces, string>({
  [MARKETPLACE_CONNECT_REQUEST]: (state, action: Action<string>) => {
    const modifiedMarketplaceId = action.payload!

    return update(state, {
      byId: update(state.byId, {
        [modifiedMarketplaceId]: { ...state.byId[modifiedMarketplaceId], status: 'connected' },
      }),
    });
  },
}, initialState);
```

The typings for `redux-actions` cause trouble sometimes.

1. When the reducer listens for more than one action (almost always), the action type must be typed twice. That's because TypeScript does not know about the relations between your action types and associated payloads.
2. One has to use the bang (`!`) operator to assert the existence of `payload`, even though we told `redux-actions` the payload is always going to be there:
 
```ts
export const connectMarketplaceRequest = createActionCreator<string>(MARKETPLACE_CONNECT_REQUEST);
```

3. The example above has worked with Redux 3.x, but it doesn't with Redux 4 anymore.

The library and its typings are both very useful. Perhaps the release of a new version of Redux might be an opportunity for us to revisit the topic of typings for `redux-actions`, especially given how much is going on in TypeScript these days.

**Comment by jake-daniels** [comment]
I agree with @karol-majewski here. We use `redux-actions` in production together with TypeScript. The redux store should be one of the key parts of the system with bulletproof types.  Could you, guys, take a look at it, adjust the types and make it work also with Redux 4?

**Comment by rcanessa89** [comment]
I'm trying but it's not looks possible at this moment, I'm using `@types/redux-actions` but the method the method `handleActions` cannot be implemented how should be. If somebody has a more complex example I would appreciate it.

**Comment by thebrodmann** [comment]
Hello all.

I don't think the pattern of redux-actions can give a full type inferring capability. at least not yet.
Also, there is no official support for typescript in redux-actions. All of these makes using redux-actions in typescript hard and misleading.

That's why I have just published [thebrodmann/deox](https://github.com/thebrodmann/deox) as a good alternative to redux-actions for typescript use cases with full power of type inferring without any type information losing.
I hope it makes sense.

**Comment by JeromeFranco** [comment]
Awesome @thebrodmann. Thanks for sharing.

**Comment by nhooey** [comment]
@rdsedmundo: Where are you importing `State` from?

**Comment by rdsedmundo** [comment]
The `State` type is your own definition of how the state shape looks like.

i.e

```
type State = {
  todos: ...;
  users: ...;
  admins: ...;
}
```

`todos`, `users` and `admins` are all reducers that you added to the store.

**Comment by jony89** [comment]
Yup, definitely there is a problem here. a workaround I found using any:

```js
const reducerMap = handleActions<State, any>(
  {
    [FIRST_TYPE]: (state: State, action: Action<PayloadOne>): State => {
      ...
    },
    [SECOND_TYPE]: (state: State, action: Action<PayloadTwo>): State => {
      ...
    },
  },
  initialState,
);
```

This still keeps my actions strongly typed.

**Comment by preco21** [comment]
I don’t know if this can be drop-in replacement to this, there’s yet another action creator library built with typescript in mind.

https://github.com/piotrwitek/typesafe-actions

**Comment by alexbrazier** [comment]
I got the types working with this

```ts
const initialState = {
  someData: false
};

type State = typeof initialState

const reducer = handleActions<State, boolean>(
  {
    [actions.request.toString()]: (state, action) => ({
      ...state,
      someData: action.payload,
    }),
  },
  initialState,
);
```

Then you can swap out `boolean` for whatever your payload is

**Comment by DragonRaider5** [comment]
Hey,

here are some TS declarations supporting:
- detection of string literal used in `const myAction = createAction('MY_ACTION', ...)`
- inference of payload type in action handlers using `ActionType<typeof myAction>` (this template expects you to have a promise resolving middleware and a thunk middleware with support for payload transformation, see `PayloadTypes<...>` type definition)
- action handler parameter checks in `handleActions()` using `const reducer = handleActions({ [myAction.toString()]: handleMyAction })` and `const handleMyAction = (state: MyState, action: ActionType<typeof myAction>): MyState => ({ ... })` (this works because the types detect the return type of `myAction.toString()` as the string literal passed to `createAction(...)`)

```typescript
// Type definitions for redux-actions 2.6.5
// Project: [~THE PROJECT NAME~]
// Definitions by: DragonRaider5 <https://github.com/DragonRaider5>

declare module 'redux-actions' {
  // createAction

  type PayloadTypes<Type> = Promise<Type> | ((state: any) => Type) | Type; // support for thunks and promises
  export interface Action<ActionName extends string, PayloadType, MetaType> {
    type: ActionName;
    payload: PayloadTypes<PayloadType>;
    meta: MetaType;
  }

  type PayloadCreator<PayloadType> = (...args: any[]) => PayloadTypes<PayloadType>;
  type MetaCreator<MetaType> = (...args: any[]) => MetaType;

  interface ActionCreator<ActionName extends string, PC extends PayloadCreator<any> | null, MC extends MetaCreator<any> | null> {
    toString: () => ActionName;
    (...args: PC extends PayloadCreator<any> ? Parameters<PC> : never[]): Action<
      ActionName,
      PC extends PayloadCreator<infer T> ? T : never,
      MC extends MetaCreator<infer U> ? U : never
    >;
  }

  export function createAction<
    ActionName extends string,
    PC extends (PayloadCreator<any> | null) = null,
    MC extends (MetaCreator<any> | null) = null
  >(type: ActionName, payloadCreator?: PC, metaCreator?: MC): ActionCreator<ActionName, PC, MC>;

  type InferPayloadType<T extends PayloadTypes<any>> = T extends PayloadTypes<infer U> ? U : never;
  export interface ActionType<T extends ActionCreator<string, any, any>> {
    type: ReturnType<T>['type'];
    payload: InferPayloadType<ReturnType<T>['payload']>;
    meta: ReturnType<T>['meta'];
  }

  // handleActions

  type ActionHandler<State, ActionName extends string> = (state: State, action: ActionType<ActionCreator<ActionName, any, any>>) => State;

  export function handleActions<State, ActionTypes extends string>(actionHandlers: {
    [key in ActionTypes]: ActionHandler<State, key>;
  }, defaultState: State): (state: State, action: Action<string, any, any>) => State;
}
```

TODO:
- [ ] support passing the state type to handleActions without having to manually declare all handled actions
- [ ] support for createActions(...) - only partial typesafe support possible, hit me up if you are interested
- [ ] support for handleAction(...) - should be 100% possible, however we don't use it, so I haven't implemented it yet

@rdsedmundo in case this helps you, you could link this post in your original post to make it easier to find for people searching google

**Comment by patoncrispy** [comment]
After trying some of the suggestions here, using typesafe-actions (the docs of which are out of date and very confusing) I decided just doing it the old-fashioned way was worth it for the type safety and it meant I didn't have to waste more time trying to figure this out with hacks. The docs on the Redux site are excellent and my actions and reducers are now type safe! Happy days! Docs: https://redux.js.org/recipes/usage-with-typescript/

**Comment by yunghoy** [comment]
> 
> 
> After trying some of the suggestions here, using typesafe-actions (the docs of which are out of date and very confusing) I decided just doing it the old-fashioned way was worth it for the type safety and it meant I didn't have to waste more time trying to figure this out with hacks. The docs on the Redux site are excellent and my actions and reducers are now type safe! Happy days! Docs: https://redux.js.org/recipes/usage-with-typescript/

I agree with you. It seems like old-fashioned method is the correct way.

**Comment by xcarpentier** [comment]
Hi,

I just published a small lib helper for creating and handling reducers with `redux-action`. I'm using it in production since a while:

👉 [redux-actionx-ts](https://github.com/xcarpentier/redux-actions-ts)  

Let me know what you think.

**Comment by nickjohngray** [comment]
Like this:

**Action**
```
import {createAction} from 'redux-actions';
import {IHistory} from '../../typings';

export enum HistoryActions {
    CHANGE_URL = 'HISTORY/CHANGE_URL',
}

export const changeURL = 
    createAction(HistoryActions.CHANGE_URL, (history: IHistory) => history);

export type changeHistoryAction = ReturnType<typeof changeURL>;

export default HistoryActions;
```

**typing**

this has the IHistory interface

export interface IHistory {
    URL: string;
}

**Reducer** 

```
import produce from 'immer';
import {handleActions} from 'redux-actions';
import {IHistory} from '../../typings';
import HistoryActions, {changeHistoryAction} from '../actions/history.action';

export const initialState = {URL: '/'};

export default handleActions<IHistory, any>(
    {
        [HistoryActions.CHANGE_URL]: produce((draft: IHistory, action: changeHistoryAction) => {
            draft.URL = action.payload.URL;
        })
    },
    initialState
);
```

**Comment by liubomyrzdrl** [comment]
https://thanarie.gitbooks.io/typescript-webpack-book/content/redux-actions.html

**Comment by leevo303** [comment]
Here is my quick solution to resolve it:

/src/types/global.d.ts
`
declare global {
  namespace ReduxActions {
    function handleActions<State>(
      reducerMap: {
        [actionType: string]: (state: State, action: Action<any>) => State;
      },
      initialState: State
    ): ReduxCompatibleReducer<State, State>;
  }
}
`
/tsconfig.json
`
{
  "compilerOptions": {
   ...
    "typeRoots": ["node_modules/@types", "src/types"],
    ...
  }
}
`

`
import { Client } from '@twilio/conversations';
import { Action, handleActions } from 'redux-actions';

import * as actions from '../actions';

export interface IMessageState {
  client?: Client;
  currentConversationId?: string;
}

export const initialState: IMessageState = {};

export default handleActions<IMessageState>(
  {
    [actions.setMessageClient.toString()]: (state = initialState, action: Action<Client>) => ({
      ...state,
      client: action.payload,
    }),
    [actions.setCurrentConversionId.toString()]: (state = initialState, action: Action<string>) => ({
      ...state,
      currentConversationId: action.payload,
    }),
  },
  initialState
);

`

**Comment by ricklancee** [comment]
So in our project we had issues with the @types/redux-action package and the typing just wasn't working so we wrote our own in a `types.d.ts`

```ts
// types.d.ts
declare module 'redux-actions' {
	import { Reducer } from 'redux';

	export function handleActions<
		TState,
		TPayloads extends { type: string; payload?: unknown }
	>(
		reducers: {
			[K in TPayloads['type']]: (
				state: TState,
				payload: TPayloads extends { type: K; payload: infer U }
					? { type: K; payload: U }
					: never
			) => TState;
		},
		initialState: TState
	): Reducer<TState>;
}
```

Usage:

```ts
// actions.ts

export const SOME_TYPE = 'SOME_TYPE';

export type SomeTypeAction = {
	type: 'SOME_TYPE';
	payload: SomeTypePayload;
};

export type SomeTypePayload = string;

export const setSomeType = (payload: SomeTypePayload): SomeTypeAction => ({
	type: SOME_TYPE,
	payload,
});
```

```ts
// reducer.ts
type State = {
  foo: string
}

const initialState: State = {
  foo: 'bar'
}

type Actions = SomeTypeAction // Add additional actions here to enforce typing.

export const list = handleActions<State, Actions>(
	{
	        // @param state is inferred as the payload from SOME_TYPE because the key matches the type in the action SomeTypeAction type.
		[SOME_TYPE]: (state, action) => ({
			...state,
			foo: action.payload // inferred correctly as a string
		}),
		// Typescript will no allow any keys here that are not in the Payloads
    }, initialState
```
