### ISSUE TITLE
2.3.1 release appears to have lodash-es issue

### ISSUE THREAD

**Issue by tquetano-r7** [redux-utilities/redux-actions#292]
I'm getting the following error on compilation:

```
ERROR in ./node_modules/redux-actions/es/createCurriedAction.js
Module not found: Error: Can't resolve 'lodash-es/fp/curryN' in '/Users/tquetano/git/idr-settings-js/node_modules/redux-actions/es'
```
And this started exactly when `2.3.1` was released.

**Comment by timche** [comment]
Fix is incoming with #293.

**Comment by foisonocean** [comment]
same problem for me

**Comment by timche** [comment]
Fixed in version [`2.3.2`](https://github.com/redux-utilities/redux-actions/releases/tag/v2.3.2). Sorry for the inconvenience.

**Comment by tquetano-r7** [comment]
No worries! Appreciate you jumping on this so quickly.

**Comment by timche** [comment]
Please let me know if it's really fixed for you.

**Comment by foisonocean** [comment]
@timche It works for me in v2.3.2. thanks for your quick fixing.
