### ISSUE TITLE
can we please remove lodash-es dependency

### ISSUE THREAD

**Issue by ajoshi0** [redux-utilities/redux-actions#300]
can we please remove lodash-es dependency is there any particular reason its there.
Its just increasing js bundle
<img width="749" alt="screen shot 2018-06-07 at 9 04 12 pm" src="https://user-images.githubusercontent.com/3833185/41138474-7645ba62-6a96-11e8-8b6c-bf35d1901b20.png">

**Comment by timche** [comment]
It is being used in this library, so it's part of it.

**Comment by ajoshi0** [comment]
I checked the lib https://github.com/redux-utilities/redux-actions/search?q=lodash-es&unscoped_q=lodash-es

is there any particular reason to use lodash-es over lodash

**Comment by newswim** [comment]
In a few instances it seems to be importing the same function from both `lodash` and `lodash-es`. I'm a little confused on the need for lodash-es as well.

**Comment by timche** [comment]
I will revisit this issue asap and try to get rid of `lodash`.

**Comment by yyynnn** [comment]
Definitely need to remove `lodash` or tree-shake unnecessary methods

**Comment by timche** [comment]
https://github.com/redux-utilities/redux-actions/pull/307 is on the way removing `lodash` completely except `lodash.curry`.

**Comment by timche** [comment]
Released in v2.5.0: https://github.com/redux-utilities/redux-actions/releases/tag/v2.5.0
