### ISSUE TITLE
Recent `camelcase` package breaks in older browsers

### ISSUE THREAD

**Issue by nowells** [redux-utilities/redux-actions#308]
https://github.com/redux-utilities/redux-actions/commit/87ff772afc8518e0554cad1b715e95a0e548b308 introduced a bug as the new camelcase package ships with ES6 features and is not transpiled, so IE11 for example will choke because it has `const` and `let` (https://unpkg.com/camelcase@5.0.0/index.js) You should use a package that is already transpiled for ES5 compatibility.

You could use https://unpkg.com/lodash.camelcase@4.3.0/index.js

**Comment by timche** [comment]
Oh no, I was a little too quick with this one, sorry. Would u mind creating a PR using `lodash.camelCase` instead or sth similar?

**Comment by nowells** [comment]
> Oh no, I was a little too quick with this one, sorry. Would u mind creating a PR using lodash.camelCase instead or sth similar?

Sure thing. Give me 5.

**Comment by michaelgillam-sd** [comment]
Getting the same error when trying to build our Docker image
