### ISSUE TITLE
React SSR handleActions  cache bug

### ISSUE THREAD

**Issue by zhangKunUserGit** [redux-utilities/redux-actions#369]
Under React SSR, when using handleActions, the current state will be cached, causing data confusion.

```
export default handleActions(
  {
    [SET_PART_DESCRIPTION_INFO]: (state, action) => ({
      ...state,
      ...action.payload
    })
  },
  initialState
);

const store: any = createStore(createReducer(), null, applyMiddleware(thunkMiddleware));

// get cache state data
store.getStates();
```
I create a store every time, but after creation, I can get the data of the previous page through getState

When I switch to the original writing method, there is no such problem

```
  switch (action.type) {
    case SET_PART_DESCRIPTION_INFO:
      return { ...state, ...action.payload };
    default:
      return state;
  }
```

Through this method, it is found that `export default handleActions` should return a global method, which causes initState to be cached, but looking through the documentation.  Does not provide a return function form.

```
// function
export default () => handleActions(
  {
    [SET_PART_DESCRIPTION_INFO]: (state, action) => ({
      ...state,
      ...action.payload
    })
  },
  initialState
);
```

I can only use native methods。

**Comment by alexander-heimbuch** [comment]
I will close this issue, if it is still an issue feel free to comment and reopen it :)
