### ISSUE TITLE
handleActions with Immer. 

### ISSUE THREAD

**Issue by sergeu90** [redux-utilities/redux-actions#371]
Hello everyone.
I want use immer with your library. I using now it so.
`
[constants.FETCH_CATEGORIES]: produce((draftState) => { setFetchCategoriesState(draftState, true)}),
`

`
[constants.FETCH_CATEGORIES_SUCCESS]: produce((draftState, { payload }) => {
    setFetchCategoriesState(draftState, false, payload);
}),
`

But I think it incorrect. In the https://immerjs.github.io/immer/docs/example-reducer in the example **produce** function created once. In my example for each actionType i creating **produce** function. Could you explain me my example correct or no. And maybe i incorrect use immer with redux-actions?
Thanks for helping

**Comment by alexander-heimbuch** [comment]
The given example (https://immerjs.github.io/immer/example-setstate#redux--immer) with immer is a very vanilla way to write reducers. So the code snippet you provided should be correct. Also see https://github.com/redux-utilities/redux-actions/issues/329 with a very similar approach.
