### ISSUE TITLE
'to-camel-case' pacakge introducing bug since it's not compatible with 'lodash.camelCase'

### ISSUE THREAD

**Issue by Rollingegg** [redux-utilities/redux-actions#385]
Hi👋 I currently use `redux-actions@2.2.1`. I want to upgrade the package to the latest version() while it performs differently to `@2.6.5` as the way to `camelCase`.
Their differences are shown as below:
![to-camel-case](https://user-images.githubusercontent.com/32197209/206956188-ee69d929-48aa-44ea-8b1f-7f30fe205927.png)
![lodash.camelCase](https://user-images.githubusercontent.com/32197209/206956205-ce99b84f-4b47-4443-8f62-05a0e54e953d.png)
This confused me a lot. Please show me the way to fix it. 
Thx😄

**Comment by alexander-heimbuch** [comment]
This should be fixed with Version 3.0
