### ISSUE TITLE
Import fails to identify entry point

### ISSUE THREAD

**Issue by madhusudhand** [redux-utilities/redux-actions#391]
In v3, package.json is missing `main` property and because of which build systems fails to compile the library.

Include `main` for entry point.

**Comment by nschild** [comment]
bump

**Comment by alexander-heimbuch** [comment]
Hey @madhusudhand,
first of all sorry for the late response. In v3 we decided to only support ES Modules. In this scenario only `exports` are used and therefore we dropped the `main` property since it also wouldn't work with non esm build systems.
